use int instead of bytes as type hint.
The i2c commands needs the address as int type. Otherwise it will raise
errors like

TypeError: '<' not supported between instances of 'bytes' and 'int'
TypeError: unsupported operand type(s) for <<: 'bytes' and 'int'

No functional change.

Signed-off-by: Jan Remmet <j.remmet@phytec.de>